[package]
name = "doot"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = { version = "1.5.3", features = ["derive"] }
clap = { version = "4.5.26", features = ["cargo"] }
colored = "3.0.0"
crossterm = "0.28.1"
ratatui = "0.29.0"
tabled = "0.17.0"
